name: Daily positive-news refresh

###############################################################################
# Triggers
###############################################################################
on:
  # Runs every day at 08:15 UTC
  schedule:
    - cron: '15 8 * * *'
  # Adds a manual “Run workflow” button in the GitHub UI
  workflow_dispatch:

###############################################################################
# Main job
###############################################################################
jobs:
  build:
    runs-on: ubuntu-latest

    # Optional Netlify build-hook URL stored as a repo secret
    env:
      NETLIFY_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}

    steps:
      # 1. Checkout repo code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Node 18
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3. Install dependencies (package.json drives versions)
      - name: Install dependencies
        run: npm install

      # 4. Run the feed fetcher to create today’s Markdown posts
      - name: Fetch positive news
        run: node fetch-feeds.js

      # 5. Commit new posts, if there were any
      - name: Commit new posts (if any)
        run: |
          git config user.email "actions@github.com"
          git config user.name  "GitHub Actions"
          git add src/posts
          if git diff --cached --quiet; then
            echo "No new posts – nothing to commit."
          else
            git commit -m "chore: daily good-news update"
          fi

      # 6. Push changes back to GitHub
      - name: Push changes
        if: success()
        run: git push

      # 7. Trigger a Netlify rebuild (optional)
      - name: Trigger Netlify build
        if: env.NETLIFY_HOOK != ''
        run: curl -s -X POST -d '{}' "$NETLIFY_HOOK"
