name: Daily positive-news refresh

on:
  schedule:
    - cron: '15 8 * * *'        # every day 08:15 UTC
  workflow_dispatch:            # manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NETLIFY_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch positive news
        run: node fetch-feeds.js

      - name: Commit new posts (if any)
        run: |
          git config user.email "actions@github.com"
          git config user.name  "GitHub Actions"
          git add src/posts
          if git diff --cached --quiet; then
            echo "No new posts – skipping commit."
          else
            git commit -m "chore: daily good-news update"
          fi

      - name: Push changes
        if: success()
        run: git push

      - name: Trigger Netlify build
        if: env.NETLIFY_HOOK != ''
        run: curl -s -X POST -d '{}' "$NETLIFY_HOOK"
